### ISSUE TITLE
Update Starscream to a recent (Swift 4 compatible) version

### ISSUE THREAD

**Issue by lla01** [sjrmanning/Birdsong#19]
Birdsong depends on Starscream 2.0.1 which doesn't compile under Swift 4

**Comment by sjrmanning** [comment]
Hey, thanks for the report about this! I'll look into this ASAP and get a new version pushed with Swift 4 support.

**Comment by sjrmanning** [comment]
I've just pushed version `0.6.0` here and published on CocoaPods. This uses Starscream 3.0 which works with Swift 4.

Please let me know if you run into any issues, and thanks again!
