### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by davidkuhta** [sjrmanning/Birdsong#2]
I was able to get Birdsong migrated to Swift 3 with relative ease 😄  So whenever you have a chance to put a `Swift-3` branch up, I'll fork and send over some PRs with detailed commits on what changed and why.

**Comment by sjrmanning** [comment]
Awesome! I've put up a `swift3` branch :) Thanks!

**Comment by davidkuhta** [comment]
Thanks, I'll clean up my Swift 3 code and update the example as well.

**Comment by sjrmanning** [comment]
Swift 3 support has been merged in as of 0.3.0 :)
