### ISSUE TITLE
Example Tweaks

### ISSUE THREAD

**Issue by optikfluffel** [sjrmanning/Birdsong#21]
Hey there, I just played around with the Example App and wanted to send a little PR to let it match the current [Phoenix.Channel](https://hexdocs.pm/phoenix/channels.html#tying-it-all-together) docs.

I then saw, that the message counter doesn't go up, so I set a breakpoint at [ViewController.swift#L86](https://github.com/sjrmanning/Birdsong/blob/master/Example/Birdsong/ViewController.swift#L86) and it seems this never get's called 🤔

I'm fairly new to Swift and Xcode, so maybe I just missed something 😅

**Comment by sjrmanning** [comment]
Thanks for taking a look! The example is probably quite out of date now. It was originally based off the Phoenix chat example, so I'll take a look at the current version soon and make sure it's still working with each other. Will update the readme to explain how the example should work with the chat example too. Thanks!

**Comment by sjrmanning** [comment]
The README has been updated with notes about how the example works with the Phoenix chat example. I've tested it and it works as expected. Let me know if you have any issues though!
