### ISSUE TITLE
Podfile.lock for example at wrong version

### ISSUE THREAD

**Issue by BryanJBryce** [sjrmanning/Birdsong#4]
`$ pod install
Analyzing dependencies
Fetching podspec for`Birdsong`from`../`
[!] Unable to satisfy the following requirements:
- `Starscream (= 1.1.3)` required by `Podfile.lock`
- `Starscream (= 1.1.1)` required by `Birdsong (0.2.2)`

It seems like you've changed the constraints of dependency `Starscream` inside your development pod `Birdsong`.
You should run `pod update Starscream` to apply changes you've made.`

**Comment by sjrmanning** [comment]
Good catch! Thanks. Sorry for the slow reply, I've been travelling lately. Will get this fixed ASAP.

Cheers!
