### ISSUE TITLE
Linux compatibility?

### ISSUE THREAD

**Issue by codeOfRobin** [sjrmanning/Birdsong#9]
AFAICT, linux compatibility shouldn't be an issue ~~as starscream works on linux~~ doesn't, but we can also use something like Perfect.org 's socket handlers. Can we start a branch that works on linux?

**Comment by codeOfRobin** [comment]
Actually, let's wait until the [Swift Server side work group](https://swift.org/server-apis/) figures this out.

**Comment by sjrmanning** [comment]
Thanks for the interest! I'd definitely like Linux compatibility. Another option is to use https://github.com/Zewo/WebSocketClient instead of Starscream for the underlying WebSockets connection, which appears to support Linux.
